jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate config.js
        run: |
          echo "const firebaseConfig = {" > config.js
          echo "  apiKey: '${{ secrets.APIKEY }}'," >> config.js
          echo "};" >> config.js
